import { Shield, Mail, MapPin, Camera, Database, Lock, Users, Eye, FileText, AlertCircle, Phone } from 'lucide-react';

function PrivacyPolicy() {
    const sections = [
        {
            id: 'interpretation',
            title: 'Interpretation and Definitions',
            icon: FileText,
            content: [
                {
                    subtitle: 'Interpretation',
                    text: 'The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.'
                },
                {
                    subtitle: 'Definitions',
                    text: 'For the purposes of this Privacy Policy:',
                    list: [
                        '<strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.',
                        '<strong>Application</strong> refers to SnapFlood, the mobile application provided by Raftwaters.',
                        '<strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Raftwaters, IIT Hyderabad.',
                        '<strong>Country</strong> refers to: India',
                        '<strong>Device</strong> means any device that can access the Service such as a smartphone, tablet, or other mobile device.',
                        '<strong>Location Data</strong> refers to geographical coordinates and location information collected from Your device.',
                        '<strong>Media Content</strong> refers to images, videos, and other multimedia content captured or uploaded through the Service.',
                        '<strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.',
                        '<strong>Service</strong> refers to the SnapFlood Application.',
                        '<strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.',
                        '<strong>You</strong> means the individual accessing or using the Service.'
                    ]
                }
            ]
        },
        {
            id: 'data-collection',
            title: 'Collecting and Using Your Personal Data',
            icon: Database,
            content: [
                {
                    subtitle: 'Types of Data Collected',
                    text: 'While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:',
                    list: [
                        'Email address',
                        'Usage Data'
                    ]
                }
            ]
        },
        {
            id: 'location-data',
            title: 'Location Data',
            icon: MapPin,
            content: [
                {
                    text: 'We collect location information when You use our Service to document flood events. This location data is essential for:',
                    list: [
                        'Geotagging flood documentation for scientific accuracy',
                        'Creating geographical flood archives',
                        'Providing location-based flood alerts and information',
                        'Supporting research and policy development'
                    ]
                },
                {
                    text: 'You can disable location services through Your device settings, but this may limit the functionality of the Service.'
                }
            ]
        },
        {
            id: 'camera-access',
            title: 'Camera and Media Access',
            icon: Camera,
            content: [
                {
                    text: 'We request access to Your device\'s camera and photo library to enable You to:',
                    list: [
                        'Capture photos and videos of flood events',
                        'Upload existing media from Your device',
                        'Document flood-related conditions safely'
                    ]
                },
                {
                    text: 'Media content uploaded through the Service becomes part of our flood documentation archive and may be used for research, analysis, and educational purposes while respecting Your privacy rights.'
                }
            ]
        },
        {
            id: 'usage-data',
            title: 'Usage Data',
            icon: Eye,
            content: [
                {
                    text: 'Usage Data is collected automatically when using the Service.'
                }
            ]
        },
        {
            id: 'use-of-data',
            title: 'Use of Your Personal Data',
            icon: Users,
            content: [
                {
                    text: 'The Company may use Personal Data for the following purposes:',
                    list: [
                        'To provide and maintain our Service, including flood documentation and archiving capabilities.',
                        'To manage Your Account: to manage Your registration and provide access to Service functionalities.',
                        'For flood research and analysis: to support scientific research, urban planning, and policy development related to flood management.',
                        'To contact You: regarding Service updates, flood alerts, or research opportunities.',
                        'To improve our Service: through data analysis and usage trend identification.',
                        'For safety purposes: to provide flood-related safety information and alerts.'
                    ]
                }
            ]
        },
        {
            id: 'sharing-data',
            title: 'Sharing of Your Personal Data',
            icon: Users,
            content: [
                {
                    text: 'We may share Your personal information in the following situations:',
                    list: [
                        '<strong>For Research Purposes:</strong> Anonymized flood documentation data may be shared with academic institutions, government agencies, and research organizations for scientific and policy research.',
                        '<strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service.',
                        '<strong>For Legal Compliance:</strong> When required by law or to protect public safety during flood emergencies.',
                        '<strong>With Your Consent:</strong> We may disclose Your personal information for any other purpose with Your explicit consent.'
                    ]
                }
            ]
        },
        {
            id: 'data-retention',
            title: 'Data Retention',
            icon: Database,
            content: [
                {
                    text: 'The Company will retain Your Personal Data only for as long as necessary for the purposes set out in this Privacy Policy. Flood documentation data may be retained for extended periods to support long-term research and historical flood analysis.'
                }
            ]
        },
        {
            id: 'security',
            title: 'Security of Your Personal Data',
            icon: Lock,
            content: [
                {
                    text: 'The security of Your Personal Data is important to Us. We implement appropriate technical and organizational security measures to protect Your personal information. However, no method of transmission over the Internet or electronic storage is 100% secure.'
                }
            ]
        },
        {
            id: 'privacy-rights',
            title: 'Your Privacy Rights',
            icon: Shield,
            content: [
                {
                    text: 'You have the right to:',
                    list: [
                        'Access and receive a copy of Your personal data',
                        'Rectify inaccurate personal data',
                        'Request deletion of Your personal data',
                        'Withdraw consent for data processing',
                        'Object to processing of Your personal data',
                        'Data portability'
                    ]
                }
            ]
        },
        {
            id: 'children',
            title: "Children's Privacy",
            icon: Shield,
            content: [
                {
                    text: 'Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.'
                }
            ]
        },
        {
            id: 'changes',
            title: 'Changes to this Privacy Policy',
            icon: FileText,
            content: [
                {
                    text: 'We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy in the app and on this page. Changes to this Privacy Policy are effective when they are posted.'
                }
            ]
        }
    ];

    return (
        <div className="min-h-screen bg-gradient-to-br from-gray-50 to-blue-50">
            {/* Hero Section */}
            <section className="pt-24 pb-12 bg-gradient-to-br from-primary-50 via-white to-blue-50">
                <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div className="text-center mb-8">
                        <div className="inline-flex items-center justify-center w-16 h-16 bg-gradient-to-br from-primary-500 to-primary-700 rounded-2xl mb-6">
                            <Shield className="w-8 h-8 text-white" />
                        </div>
                        <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
                            Privacy Policy
                        </h1>
                        <p className="text-lg text-gray-700 max-w-3xl mx-auto leading-relaxed">
                            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the SnapFlood Service and tells You about Your privacy rights and how the law protects You.
                        </p>
                    </div>
                </div>
            </section>

            {/* About SnapFlood Section */}
            <section className="py-12">
                <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div className="bg-white rounded-2xl shadow-lg p-8 md:p-10 mb-8">
                        <h2 className="text-2xl font-bold text-gray-900 mb-4">About SnapFlood</h2>
                        <div className="space-y-4 text-gray-700 leading-relaxed">
                            <p>
                                SnapFlood is an innovative flood documentation application developed by <span className="font-semibold text-primary-700">RAFT (Rainfall-runoff Analysis and Forecasting Tools)</span> at IIT Hyderabad. The app was developed as part of projects funded by the Government of India's Department of Science and Technology (DST-SPLICE, Climate Change Programme) National Network Programme on Urban Climate (NUC) and the ongoing AI CoE for sustainable cities project.
                            </p>
                            <p>
                                Unlike traditional riverine flood monitoring methods, SnapFlood addresses the unique challenges of urban flooding by enabling users to safely document flood events through images and videos. This creates a valuable flood archive for scientific, engineering, and policy applications worldwide.
                            </p>
                        </div>
                        <div className="mt-6 pt-6 border-t border-gray-200">
                            <p className="text-sm text-gray-600">
                                <strong>Important:</strong> We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                            </p>
                        </div>
                    </div>
                </div>
            </section>

            {/* Main Privacy Sections */}
            <section className="py-8 pb-16">
                <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 space-y-6">
                    {sections.map((section) => {
                        const Icon = section.icon;
                        return (
                            <div key={section.id} id={section.id} className="bg-white rounded-xl shadow-md p-6 md:p-8">
                                <div className="flex items-start gap-4 mb-4">
                                    <div className="w-12 h-12 bg-gradient-to-br from-primary-500 to-primary-700 rounded-xl flex items-center justify-center flex-shrink-0">
                                        <Icon className="w-6 h-6 text-white" />
                                    </div>
                                    <h2 className="text-2xl font-bold text-gray-900 pt-2">{section.title}</h2>
                                </div>

                                <div className="space-y-4 ml-16">
                                    {section.content.map((item, idx) => (
                                        <div key={idx}>
                                            {item.subtitle && (
                                                <h3 className="text-lg font-semibold text-gray-900 mb-2">{item.subtitle}</h3>
                                            )}
                                            {item.text && (
                                                <p className="text-gray-700 leading-relaxed mb-3">{item.text}</p>
                                            )}
                                            {item.list && (
                                                <ul className="space-y-2 ml-4">
                                                    {item.list.map((listItem, listIdx) => (
                                                        <li key={listIdx} className="flex items-start gap-2 text-gray-700">
                                                            <span className="text-primary-600 mt-1.5 flex-shrink-0">•</span>
                                                            <span dangerouslySetInnerHTML={{ __html: listItem }} />
                                                        </li>
                                                    ))}
                                                </ul>
                                            )}
                                        </div>
                                    ))}
                                </div>
                            </div>
                        );
                    })}
                </div>
            </section>

            {/* Safety Reminder */}
            <section className="py-12 bg-white">
                <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div className="bg-gradient-to-br from-orange-50 to-red-50 border-2 border-orange-200 rounded-xl p-6 md:p-8">
                        <div className="flex items-start gap-4">
                            <div className="w-12 h-12 bg-gradient-to-br from-orange-500 to-red-600 rounded-xl flex items-center justify-center flex-shrink-0">
                                <AlertCircle className="w-6 h-6 text-white" />
                            </div>
                            <div>
                                <h3 className="text-xl font-bold text-gray-900 mb-2">Safety First</h3>
                                <p className="text-gray-700 leading-relaxed">
                                    Remember to always prioritize your safety when documenting flood events. Never enter dangerous flood waters or put yourself at risk. SnapFlood is designed to help create a valuable flood archive while keeping you safe.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* Footer Note */}
            <section className="py-8 bg-white border-t border-gray-200">
                <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
                    <p className="text-sm text-gray-600">
                        Last Updated: February 2024 • SnapFlood by RAFT, IIT Hyderabad
                    </p>
                </div>
            </section>

            {/* Contact Section */}
            <section className="py-12 bg-gradient-to-br from-primary-600 to-primary-800">
                <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div className="text-center text-white">
                        <h2 className="text-3xl font-bold mb-6">Contact Us</h2>
                        <p className="text-lg text-primary-100 mb-8">
                            If you have any questions about this Privacy Policy, You can contact us:
                        </p>
                        <div className="flex flex-col sm:flex-row items-center justify-center gap-6 mb-8">
                            <a
                                href="mailto:snapflood@iith.ac.in"
                                className="flex items-center gap-2 bg-white text-primary-700 px-6 py-3 rounded-lg font-semibold hover:bg-primary-50 transition-colors"
                            >
                                <Mail className="w-5 h-5" />
                                snapflood@iith.ac.in
                            </a>
                            <a
                                href="https://play.google.com"
                                target="_blank"
                                rel="noopener noreferrer"
                                className="flex items-center gap-2 bg-gray-900 text-white px-6 py-3 rounded-lg font-semibold hover:bg-gray-800 transition-colors"
                            >
                                <Phone className="w-5 h-5" />
                                Get The App: Playstore
                            </a>
                        </div>
                    </div>
                </div>
            </section>

        </div>
    );
}

export default PrivacyPolicy;